# Generated by Django 3.2 on 2022-05-24 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pageCount', models.IntegerField()),
                ('published_date', models.DateField(default=datetime.datetime.now)),
                ('thumbnail', models.CharField(max_length=256)),
            ],
        ),
    ]
